inherit_from: ./configs/Dynamic/Wild_SLAM_iPhone/wild_slam_iphone.yaml
scene: iphone_wandering

data:
  input_folder: ROOT_FOLDER_PLACEHOLDER/wandering

cam:
  fx: 1341.6507568359375
  fy: 1341.6507568359375
  cx: 961.001708984375
  cy: 730.54937744140625